#! /bin/bash

commit_msg="${1:-$(date '+%m-%d-%Y %H:%M:%S')}"

dotfile_path="$HOME/.dotfiles/.config"
mkdir -p "$dotfile_path"

echo -e "\033[1;92mSyncing all config to dotfiles: \n"

sync_file() {
    local src="$HOME/.config/$1"
    local dest="$dotfile_path/$2"

    if [ -e "$src" ]; then
        mkdir -p "$dest"
        rsync -avhP --delete "$src" "$dest"
    else
        echo -e "\033[1; 93mWarning: Source $src does not exist. Skipping...\033[0m"
    fi
}

#          ╔══════════════════════════════════════════════════════════╗
#          ║                          Editor                          ║
#          ╚══════════════════════════════════════════════════════════╝
sync_file "doom/" "doom/"
sync_file "nvim/" "nvim/"

#          ╔══════════════════════════════════════════════════════════╗
#          ║                          Fonts                           ║
#          ╚══════════════════════════════════════════════════════════╝
sync_file ".fonts/" ".fonts/"

#          ╔══════════════════════════════════════════════════════════╗
#          ║                         Terminal                         ║
#          ╚══════════════════════════════════════════════════════════╝
# ───────────────────────────────── Yazi ─────────────────────────────────
sync_file "yazi/" "yazi/"
sync_file "fish/" "fish/"
sync_file "fastfetch/" "fastfetch/"
sync_file "wezterm/" "wezterm/"
sync_file "kitty/" "kitty/"
sync_file "starship.toml" "starship.toml"

#          ╔══════════════════════════════════════════════════════════╗
#          ║                          System                          ║
#          ╚══════════════════════════════════════════════════════════╝
sync_file "waybar/" "waybar/"
sync_file "ironbar/" "ironbar/"
sync_file "swaync/" "swaync/"
sync_file "swaylock/" "swaylock/"
sync_file "niri/" "niri/"
sync_file "systemd/" "systemd/"

echo -e "\n\033[1;94mArch Packages install list:\n"
paru -Qeq | tee "$dotfile_path/my_arch_package"

echo -e "\n\033[1;96mGit Messages:\n"
pushd $dotfile_path >/dev/null
cd ..
git add .
git commit -m "$commit_msg"
git push origin main
echo -e "\033[0m"

popd >/dev/null
