#! /bin/bash

dotfile_path="$HOME/Documents/dotfiles/.config"
mkdir -p $dotfile_path

echo -e "\033[1;93mSyncing all config to dotfiles: \n"
# ──────────────────────────────── Fonts ──────────────────────────────
rsync -avhP --delete $HOME/.fonts/ "$dotfile_path/.fonts/"
# ──────────────────────────────── Neovim ────────────────────────────────
rsync -avhP --delete $HOME/.config/nvim/ "$dotfile_path/nvim/"
# ───────────────────────────────── Yazi ─────────────────────────────────
rsync -avhP --delete $HOME/.config/yazi/ "$dotfile_path/yazi/"
#───────────────────────────────── fish ─────────────────────────────────
rsync -avhP --delete $HOME/.config/fish/ "$dotfile_path/fish/"
# ────────────────────────────── fastfetch ────────────────────────────
rsync -avhP --delete $HOME/.config/fastfetch/ "$dotfile_path/fastfetch/"
# ─────────────────────────────── wezterm ─────────────────────────────
rsync -avhP --delete $HOME/.config/wezterm/ "$dotfile_path/wezterm/"
# ──────────────────────────────── vivify ────────────────────────────────
rsync -avhP --delete $HOME/.config/vivify/ "$dotfile_path/vivify/"
# ─────────────────────────────── starship ───────────────────────────────
rsync -avhP --delete $HOME/.config/starship.toml "$dotfile_path/"

echo -e "\n\033[1;94mArch Packages install list:\n"
paru -Qeq | tee "$dotfile_path/my_arch_package"

echo -e "\n\033[1;92mGit Messages:\n"
pushd $dotfile_path >/dev/null
cd ..
git add .
git commit -m "$(date '+%m-%d-%Y %H:%M:%S')"
git push origin main
echo -e "\033[0m"

popd >/dev/null
