#! /bin/bash

dotfile_path="$HOME/Documents/dotfiles"
mkdir -p $dotfile_path

# ──────────────────────────────── Fonts ──────────────────────────────
rsync -avhP --delete $HOME/.fonts/ "$dotfile_path/.fonts/"
# ──────────────────────────────── Neovim ────────────────────────────────
rsync -avhP --delete $HOME/.config/nvim/ "$dotfile_path/nvim/"
# ───────────────────────────────── Yazi ─────────────────────────────────
rsync -avhP --delete $HOME/.config/yazi/ "$dotfile_path/yazi/"
#───────────────────────────────── fish ─────────────────────────────────
rsync -avhP --delete $HOME/.config/fish/ "$dotfile_path/fish/"
# ─────────────────────────────── wezterm ─────────────────────────────
rsync -avhP --delete $HOME/.config/wezterm/ "$dotfile_path/wezterm/"
# ──────────────────────────────── vivify ────────────────────────────────
rsync -avhP --delete $HOME/.config/vivify/ "$dotfile_path/vivify/"
# ─────────────────────────────── starship ───────────────────────────────
rsync -avhP --delete $HOME/.config/starship.toml "$dotfile_path/"

paru -Qeq | tee "$dotfile_path/my_arch_package"
pushd $dotfile_path >/dev/null
git add .
git commit -m "$(date '+%m-%d-%Y %H:%M:%S')"
git push origin main

popd >/dev/null
