#! /bin/bash

if ! pacman -Q paru >/dev/null 2>&1; then
  sudo pacman -S --needed base-devel
  pushd /tmp >/dev/null
  git clone https://aur.archlinux.org/paru.git
  cd paru
  makepkg -si
  popd >/dev/null
else
  echo -e "\033[1;92mparu is already installed.\033[0m"
fi

dotfile_path="$HOME/Documents/dotfile"

xargs -a "$dotfile_path/my_arch_package" paru -S --needed

# ──────────────────────────────── Neovim ────────────────────────────────
neovim_path="$HOME/.config/nvim/"
mkdir -p "$neovim_path"
rsync -avhP "$dotfile_path/nvim/" "$neovim_path" --exclude ".git" --exclude ".gitignore"
# ───────────────────────────────── Yazi ─────────────────────────────────
yazi_path="$HOME/.config/yazi/"
mkdir -p "$yazi_path"
rsync -avhP "$dotfile_path/yazi/" "$yazi_path" --exclude ".git" --exclude ".gitignore"
# ───────────────────────────────── fish ─────────────────────────────────
fish_path="$HOME/.config/fish/"
mkdir -p "$fish_path"
rsync -avhP "$dotfile_path/fish/" "$fish_path" --exclude ".git" --exclude ".gitignore"
# ─────────────────────────────── wezterm ─────────────────────────────
wezterm_path="$HOME/.config/wezterm/"
mkdir -p "$wezterm_path"
rsync -avhP "$dotfile_path/wezterm/" "$wezterm_path"
# ─────────────────────────────── vivify ─────────────────────────────
vivify_path="$HOME/.config/vivify/"
mkdir -p "$vivify_path"
rsync -avhP "$dotfile_path/vivify/" "$vivify_path"
# ─────────────────────────────── starship ───────────────────────────────
starship_path="$HOME/.config/"
mkdir -p "$starship_path"
rsync -avhP "$dotfile_path/starship.toml" "$starship_path" --exclude ".git" --exclude ".gitignore"
