position = "top"
height = 20


[[start]]
type = "music"
icon_size = 16

[start.truncate]
mode = "end"
max_length = 30

# [start.marquee]
# enable = true
# max_length = 30

[[center]]
type = "workspaces"
sort = "name"

[center.name_map]
1 = "  "
2 = "  "
3 = "  "
4 = "  "
5 = "  "
6 = "  "
7 = "  "
8 = "  "
9 = "  "
# web = "  "
# code = "  "
# term = "  "
# work = "  "
# music = "  "
# docs = "  "

[[end]]
type = "focused"
icon_size = 24

[end.truncate]
mode = "end"
length = 5
max_length = 20

[[end]]
type = "tray"
icon_size = 16

[[end]]
type = "script"
cmd = "/home/shaogu/.cargo/bin/weather"
interval = 1800000

[[end]]
type = "battery"
format = "{percentage}%"

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100
truncate = "middle"

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

[[end]]
type = "notifications"
show_count = true

[end.icons]
closed_none = "󰍥"
closed_some = "󱥂"
closed_dnd = "󱅯"
open_none = "󰍡"
open_some = "󱥁"
open_dnd = "󱅮"


[[end]]
type = "clock"
format = " %H:%M"
format_popup = "%m-%d-%Y"
